# Generated by Django 3.1 on 2020-08-26 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('castle_id', models.AutoField(primary_key=True, serialize=False)),
                ('castle_name', models.CharField(default='Castle Name', max_length=40)),
                ('total_blocks', models.IntegerField(default=250)),
                ('completed_blocks', models.IntegerField(default=0)),
                ('banner_color', models.CharField(default='blue', max_length=25)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
