# Generated by Django 3.1 on 2020-08-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castledoro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castle',
            old_name='associated_user',
            new_name='associated_user_id',
        ),
        migrations.AddField(
            model_name='castle',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
