# Generated by Django 3.1 on 2020-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castledoro', '0002_auto_20200827_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castle',
            name='total_blocks',
            field=models.IntegerField(default=25),
        ),
    ]
