# Generated by Django 3.1 on 2020-11-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castledoro', '0003_auto_20200929_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castle',
            name='banner_color',
        ),
        migrations.AlterField(
            model_name='castle',
            name='total_blocks',
            field=models.IntegerField(default=165),
        ),
    ]
